services:
  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./requirements/nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./certs:/etc/nginx/certs:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  # wordpress:
  #   container_name: wordpress
  #   restart: on-failure
  #   build:
  #     context: ./requirements/wordpress
    
