services:
  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    build:
      context: ./requirements/nginx
    ports:
      - 8443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mysql_name
      - mysql_user
      - mysql_password
      - mysql_root_password

  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    secrets:
      - mysql_name
      - mysql_user
      - mysql_password
      - mysql_root_password
    

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  mariadb:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_name:
    file: ./secrets/mysql_name
  mysql_user:
    file: ./secrets/mysql_user
  mysql_password:
    file: ./secrets/mysql_password